name: 刷步数

on:
  workflow_dispatch:
  schedule:
    - cron: 0 8 * * *

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v1
      - name: 'Post Sports'
        run: bash ./sports.sh
      - name: 'Get Date'
        run: echo "REPORT_DATE=$(TZ=':Asia/Bei Jing' date '+%Y-%m-%d %T')" >> $GITHUB_ENV
      - name: 'Send mail'
        uses: dawidd6/action-send-mail@master
        with:
          server_address: smtp.163.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: Xiao Mi Sports 
          body: 成功
          to: yuwangifeng@163.com
          from: GitHub Actions
          content_type: text/html
